# Generated by Django 3.1.7 on 2021-03-15 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bradt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 22, 59, 51, 811961)),
        ),
    ]
